"""v2_initial_schema

Revision ID: 568156c964dd
Revises: 
Create Date: 2026-09-22 06:01:19.305154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_cleanup_queue_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cleanup_queue')),
    sa.UniqueConstraint('backend', 'storage_key', name='uq_cleanup_backend_key')
    )
    with op.batch_alter_table('cleanup_queue', schema=None) as batch_op:
        batch_op.create_index('ix_cleanup_queue_next_attempt', ['next_attempt_at_ms'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_key', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('blocked_until_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('count >= 0', name=op.f('ck_rate_limit_buckets_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_buckets')),
    sa.UniqueConstraint('bucket_key', name=op.f('uq_rate_limit_buckets_bucket_key'))
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_buckets_window', ['window_started_at_ms'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('username_key', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=120), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('calendar', sa.String(length=16), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until_ms', sa.BigInteger(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_login_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("calendar IN ('jalali', 'gregorian')", name=op.f('ck_users_calendar_valid')),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint('age IS NULL OR (age >= 1 AND age <= 120)', name=op.f('ck_users_age_range')),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_non_negative')),
    sa.CheckConstraint('storage_used_bytes >= 0', name=op.f('ck_users_storage_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username_key', name=op.f('uq_users_username_key'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error', 'security')", name=op.f('ck_audit_logs_severity_valid')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at_ms'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_user_id', 'created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at_ms'), ['created_at_ms'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('expires_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at_ms'), ['expires_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_auth_sessions_user_id_expires', ['user_id', 'expires_at_ms'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('live_files_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_token', sa.String(length=43), nullable=True),
    sa.Column('public_token_created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('timing_mode', sa.String(length=16), nullable=False),
    sa.Column('global_seconds', sa.Integer(), nullable=False),
    sa.Column('order_mode', sa.String(length=16), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("order_mode IN ('manual', 'alpha', 'age')", name=op.f('ck_rooms_order_mode_valid')),
    sa.CheckConstraint("timing_mode IN ('global', 'individual')", name=op.f('ck_rooms_timing_mode_valid')),
    sa.CheckConstraint('NOT public_enabled OR public_token IS NOT NULL', name=op.f('ck_rooms_public_requires_token')),
    sa.CheckConstraint('capacity >= 1', name=op.f('ck_rooms_capacity_positive')),
    sa.CheckConstraint('global_seconds >= 10 AND global_seconds <= 86400', name=op.f('ck_rooms_global_seconds_range')),
    sa.CheckConstraint('storage_used_bytes >= 0', name=op.f('ck_rooms_storage_non_negative')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_rooms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('public_token', name=op.f('uq_rooms_public_token'))
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_rooms_owner_id_id_desc', ['owner_id', 'id'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('speaking_seconds', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('finished_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("gender IN ('', 'male', 'female', 'other')", name=op.f('ck_speakers_gender_valid')),
    sa.CheckConstraint('age IS NULL OR (age >= 1 AND age <= 120)', name=op.f('ck_speakers_age_range')),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_speakers_order_index_non_negative')),
    sa.CheckConstraint('speaking_seconds >= 10 AND speaking_seconds <= 86400', name=op.f('ck_speakers_speaking_seconds_range')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_speakers_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakers')),
    sa.UniqueConstraint('room_id', 'order_index', name='uq_speaker_room_order')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_room_id'), ['room_id'], unique=False)
        batch_op.create_index('ix_speakers_room_id_name', ['room_id', 'name'], unique=False)

    op.create_table('room_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('current_speaker_id', sa.Integer(), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('awaiting_decision', sa.Boolean(), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('elapsed_ms', sa.BigInteger(), nullable=False),
    sa.Column('overtime_ms', sa.BigInteger(), nullable=False),
    sa.Column('stop_reason', sa.String(length=24), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("stop_reason IN ('', 'paused', 'time_up', 'finished', 'session_completed', 'switched')", name=op.f('ck_room_states_stop_reason_valid')),
    sa.CheckConstraint('current_index >= 0', name=op.f('ck_room_states_current_index_non_negative')),
    sa.CheckConstraint('elapsed_ms >= 0', name=op.f('ck_room_states_elapsed_non_negative')),
    sa.CheckConstraint('overtime_ms >= 0', name=op.f('ck_room_states_overtime_non_negative')),
    sa.ForeignKeyConstraint(['current_speaker_id'], ['speakers.id'], name=op.f('fk_room_states_current_speaker_id_speakers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_states_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_states')),
    sa.UniqueConstraint('room_id', name=op.f('uq_room_states_room_id'))
    )
    with op.batch_alter_table('room_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_states_current_speaker_id'), ['current_speaker_id'], unique=False)

    op.create_table('speaker_timer_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.BigInteger(), nullable=False),
    sa.Column('overtime_ms', sa.BigInteger(), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('elapsed_ms >= 0', name=op.f('ck_speaker_timer_states_elapsed_non_negative')),
    sa.CheckConstraint('overtime_ms >= 0', name=op.f('ck_speaker_timer_states_overtime_non_negative')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_speaker_timer_states_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_speaker_timer_states_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_timer_states')),
    sa.UniqueConstraint('room_id', 'speaker_id', name='uq_timer_room_speaker')
    )
    with op.batch_alter_table('speaker_timer_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speaker_timer_states_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speaker_timer_states_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('speech_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_type', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('speaker_name', sa.String(length=120), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("upload_type IN ('common', 'speaker', 'recording')", name=op.f('ck_speech_files_upload_type_valid')),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name=op.f('ck_speech_files_duration_non_negative')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_speech_files_size_non_negative')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_speech_files_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_speech_files_speaker_id_speakers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speech_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_speech_files_storage_key'))
    )
    with op.batch_alter_table('speech_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speech_files_room_id'), ['room_id'], unique=False)
        batch_op.create_index('ix_speech_files_room_upload_created', ['room_id', 'upload_type', 'created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_speech_files_speaker_id'), ['speaker_id'], unique=False)
        batch_op.create_index('ix_speech_files_upload_type_created', ['upload_type', 'created_at_ms'], unique=False)

    op.create_table('recording_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('speaker_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('chunk_seq', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('recorded_ms', sa.BigInteger(), nullable=False),
    sa.Column('active_since_ms', sa.BigInteger(), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_chunk_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('ended_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('final_file_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('recording', 'paused', 'finalizing', 'saved', 'discarded', 'failed', 'recovered')", name=op.f('ck_recording_sessions_status_valid')),
    sa.CheckConstraint('bytes_received >= 0', name=op.f('ck_recording_sessions_bytes_non_negative')),
    sa.CheckConstraint('chunk_seq >= 0', name=op.f('ck_recording_sessions_chunk_seq_non_negative')),
    sa.CheckConstraint('recorded_ms >= 0', name=op.f('ck_recording_sessions_recorded_ms_non_negative')),
    sa.ForeignKeyConstraint(['final_file_id'], ['speech_files.id'], name=op.f('fk_recording_sessions_final_file_id_speech_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_recording_sessions_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_recording_sessions_speaker_id_speakers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_sessions'))
    )
    with op.batch_alter_table('recording_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recording_sessions_room_id'), ['room_id'], unique=False)
        batch_op.create_index('ix_recording_sessions_room_status', ['room_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recording_sessions_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('recording_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('seq >= 0', name=op.f('ck_recording_chunks_seq_non_negative')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_recording_chunks_size_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['recording_sessions.id'], name=op.f('fk_recording_chunks_session_id_recording_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_chunks')),
    sa.UniqueConstraint('session_id', 'seq', name='uq_chunk_session_seq'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_recording_chunks_storage_key'))
    )
    with op.batch_alter_table('recording_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recording_chunks_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recording_chunks_session_id'))

    op.drop_table('recording_chunks')
    with op.batch_alter_table('recording_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recording_sessions_speaker_id'))
        batch_op.drop_index('ix_recording_sessions_room_status')
        batch_op.drop_index(batch_op.f('ix_recording_sessions_room_id'))

    op.drop_table('recording_sessions')
    with op.batch_alter_table('speech_files', schema=None) as batch_op:
        batch_op.drop_index('ix_speech_files_upload_type_created')
        batch_op.drop_index(batch_op.f('ix_speech_files_speaker_id'))
        batch_op.drop_index('ix_speech_files_room_upload_created')
        batch_op.drop_index(batch_op.f('ix_speech_files_room_id'))

    op.drop_table('speech_files')
    with op.batch_alter_table('speaker_timer_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speaker_timer_states_speaker_id'))
        batch_op.drop_index(batch_op.f('ix_speaker_timer_states_room_id'))

    op.drop_table('speaker_timer_states')
    with op.batch_alter_table('room_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_states_current_speaker_id'))

    op.drop_table('room_states')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index('ix_speakers_room_id_name')
        batch_op.drop_index(batch_op.f('ix_speakers_room_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_owner_id_id_desc')
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user_id_expires')
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at_ms'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at_ms'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index('ix_audit_logs_action_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))

    op.drop_table('users')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_buckets_window')

    op.drop_table('rate_limit_buckets')
    with op.batch_alter_table('cleanup_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_cleanup_queue_next_attempt')

    op.drop_table('cleanup_queue')
    # ### end Alembic commands ###
